/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/home/ben/Repositories/vuepress-wiki-branch/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-67bd9eb8",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67bd9eb8").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-35957706",
    path: "/algebra/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35957706").then(next)
    },
  },
  {
    path: "/algebra/index.html",
    redirect: "/algebra/"
  },
  {
    name: "v-38e50476",
    path: "/algebra/category.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38e50476").then(next)
    },
  },
  {
    name: "v-39371d7a",
    path: "/algebra/commutative.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39371d7a").then(next)
    },
  },
  {
    name: "v-6e377c63",
    path: "/algebra/group.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e377c63").then(next)
    },
  },
  {
    name: "v-19f2d7fa",
    path: "/algebra/lie.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19f2d7fa").then(next)
    },
  },
  {
    name: "v-6512bae7",
    path: "/algebra/noncommutative.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6512bae7").then(next)
    },
  },
  {
    name: "v-7d51f767",
    path: "/algebra/representation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d51f767").then(next)
    },
  },
  {
    name: "v-93f29fb0",
    path: "/geometry/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-93f29fb0").then(next)
    },
  },
  {
    path: "/geometry/index.html",
    redirect: "/geometry/"
  },
  {
    name: "v-e514d642",
    path: "/geometry/algebraic/algebraic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e514d642").then(next)
    },
  },
  {
    name: "v-ad713182",
    path: "/geometry/algebraic/git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ad713182").then(next)
    },
  },
  {
    name: "v-5c45b9f2",
    path: "/geometry/algebraic/schemes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c45b9f2").then(next)
    },
  },
  {
    name: "v-34fbce3d",
    path: "/geometry/algebraic/sheaves.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34fbce3d").then(next)
    },
  },
  {
    name: "v-69f7e097",
    path: "/geometry/algebraic/varieties.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69f7e097").then(next)
    },
  },
  {
    name: "v-7a9346a7",
    path: "/geometry/complex/complex.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a9346a7").then(next)
    },
  },
  {
    name: "v-365cddaa",
    path: "/geometry/differential/differential.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-365cddaa").then(next)
    },
  },
  {
    name: "v-0e3f54ab",
    path: "/geometry/symplectic/symplectic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e3f54ab").then(next)
    },
  },
  {
    name: "v-0bd0e011",
    path: "/home.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0bd0e011").then(next)
    },
  },
  {
    name: "v-239fffe3",
    path: "/miscellaneous/manuals.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-239fffe3").then(next)
    },
  },
  {
    name: "v-5119d75f",
    path: "/miscellaneous/manuals/pypdfocr.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5119d75f").then(next)
    },
  },
  {
    name: "v-cc9d6bfa",
    path: "/miscellaneous/programming/linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cc9d6bfa").then(next)
    },
  },
  {
    name: "v-8cbe56b2",
    path: "/miscellaneous/programming/vuepress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8cbe56b2").then(next)
    },
  },
  {
    name: "v-b8e4eb70",
    path: "/physics/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b8e4eb70").then(next)
    },
  },
  {
    path: "/physics/index.html",
    redirect: "/physics/"
  },
  {
    name: "v-ba0c597a",
    path: "/physics/gauge.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba0c597a").then(next)
    },
  },
  {
    name: "v-9f5d68a2",
    path: "/physics/quantisation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f5d68a2").then(next)
    },
  },
  {
    name: "v-6bb9ea5d",
    path: "/physics/string.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bb9ea5d").then(next)
    },
  },
  {
    name: "v-1e8142fa",
    path: "/physics/supersymmetry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e8142fa").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]