/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Wiki",
        "tagLine": "Create and publish fast, feature-rich sites in minutes",
        "heroImage": "/icon.png",
        "actionText": "Enter the wiki! →",
        "actionLink": "/home"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-f236b05e",
      "path": "/",
      "headers": [
        {
          "level": 3,
          "title": "By Ben Brown",
          "slug": "by-ben-brown"
        }
      ],
      "lastUpdated": "11/25/2019, 8:35:35 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/algebra/",
      "relativePath": "algebra/README.md",
      "key": "v-00212e1f",
      "path": "/algebra/",
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Category Theory",
      "frontmatter": {},
      "regularPath": "/algebra/category.html",
      "relativePath": "algebra/category.md",
      "key": "v-c308dce8",
      "path": "/algebra/category.html",
      "headers": [
        {
          "level": 2,
          "title": "Constructions",
          "slug": "constructions"
        },
        {
          "level": 3,
          "title": "Coproduct",
          "slug": "coproduct"
        }
      ],
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Commutative Algebra",
      "frontmatter": {},
      "regularPath": "/algebra/commutative.html",
      "relativePath": "algebra/commutative.md",
      "key": "v-693053ca",
      "path": "/algebra/commutative.html",
      "headers": [
        {
          "level": 2,
          "title": "Algebras",
          "slug": "algebras"
        }
      ],
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Group Theory",
      "frontmatter": {},
      "regularPath": "/algebra/group.html",
      "relativePath": "algebra/group.md",
      "key": "v-a9d49d2c",
      "path": "/algebra/group.html",
      "headers": [
        {
          "level": 2,
          "title": "Actions",
          "slug": "actions"
        },
        {
          "level": 2,
          "title": "Group Action",
          "slug": "group-action"
        },
        {
          "level": 3,
          "title": "Free Action",
          "slug": "free-action"
        },
        {
          "level": 3,
          "title": "Semifree Action",
          "slug": "semifree-action"
        },
        {
          "level": 2,
          "title": "Linear Algebraic Groups",
          "slug": "linear-algebraic-groups"
        },
        {
          "level": 3,
          "title": "Affine Algebraic Group",
          "slug": "affine-algebraic-group"
        },
        {
          "level": 3,
          "title": "Borel Subgroup",
          "slug": "borel-subgroup"
        }
      ],
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Lie Theory",
      "frontmatter": {},
      "regularPath": "/algebra/lie.html",
      "relativePath": "algebra/lie.md",
      "key": "v-78de648a",
      "path": "/algebra/lie.html",
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Non-Commutative Algebra",
      "frontmatter": {},
      "regularPath": "/algebra/noncommutative.html",
      "relativePath": "algebra/noncommutative.md",
      "key": "v-4c565c2e",
      "path": "/algebra/noncommutative.html",
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Representation Theory",
      "frontmatter": {},
      "regularPath": "/algebra/representation.html",
      "relativePath": "algebra/representation.md",
      "key": "v-649598ae",
      "path": "/algebra/representation.html",
      "headers": [
        {
          "level": 2,
          "title": "Constructions",
          "slug": "constructions"
        },
        {
          "level": 3,
          "title": "Tensor Product",
          "slug": "tensor-product"
        }
      ],
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Geometry",
      "frontmatter": {},
      "regularPath": "/geometry/",
      "relativePath": "geometry/README.md",
      "key": "v-0c810501",
      "path": "/geometry/",
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Algebraic Geometry",
      "frontmatter": {},
      "regularPath": "/geometry/algebraic/algebraic.html",
      "relativePath": "geometry/algebraic/algebraic.md",
      "key": "v-35a683a6",
      "path": "/geometry/algebraic/algebraic.html",
      "headers": [
        {
          "level": 2,
          "title": "Algebraic Varieties",
          "slug": "algebraic-varieties"
        },
        {
          "level": 3,
          "title": "Quasi-Projective Varieties",
          "slug": "quasi-projective-varieties"
        },
        {
          "level": 3,
          "title": "Morphisms",
          "slug": "morphisms"
        },
        {
          "level": 2,
          "title": "Birational Geometry",
          "slug": "birational-geometry"
        },
        {
          "level": 3,
          "title": "Projective Morphisms",
          "slug": "projective-morphisms"
        },
        {
          "level": 3,
          "title": "Birational Morphisms",
          "slug": "birational-morphisms"
        },
        {
          "level": 3,
          "title": "Rational Maps",
          "slug": "rational-maps"
        },
        {
          "level": 3,
          "title": "Birational Equivalence",
          "slug": "birational-equivalence"
        },
        {
          "level": 2,
          "title": "Types of Morphisms",
          "slug": "types-of-morphisms"
        },
        {
          "level": 3,
          "title": "Closed Embeddings",
          "slug": "closed-embeddings"
        }
      ],
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Geometric Invariant Theory",
      "frontmatter": {},
      "regularPath": "/geometry/algebraic/git.html",
      "relativePath": "geometry/algebraic/git.md",
      "key": "v-dee9eef4",
      "path": "/geometry/algebraic/git.html",
      "headers": [
        {
          "level": 2,
          "title": "Linearisations",
          "slug": "linearisations"
        },
        {
          "level": 3,
          "title": "$G$-linearisation",
          "slug": "linearisation"
        },
        {
          "level": 3,
          "title": "Picard Groups of Products",
          "slug": "picard-groups-of-products"
        },
        {
          "level": 2,
          "title": "Algebraic Symplectic Reduction",
          "slug": "algebraic-symplectic-reduction"
        },
        {
          "level": 3,
          "title": "Algebraic Symplectic Reduction",
          "slug": "algebraic-symplectic-reduction-2"
        }
      ],
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Schemes",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/geometry/algebraic/schemes.html",
      "relativePath": "geometry/algebraic/schemes.md",
      "key": "v-222ae564",
      "path": "/geometry/algebraic/schemes.html",
      "headers": [
        {
          "level": 2,
          "title": "Projective Schemes",
          "slug": "projective-schemes"
        },
        {
          "level": 3,
          "title": "The Proj Construction",
          "slug": "the-proj-construction"
        },
        {
          "level": 3,
          "title": "Projective Scheme(s) over an Affine Scheme",
          "slug": "projective-scheme-s-over-an-affine-scheme"
        },
        {
          "level": 3,
          "title": "Truncated Rings and the Veronese Embedding",
          "slug": "truncated-rings-and-the-veronese-embedding"
        },
        {
          "level": 2,
          "title": "References",
          "slug": "references"
        }
      ],
      "lastUpdated": "11/25/2019, 8:35:35 PM"
    },
    {
      "title": "Sheaves",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/geometry/algebraic/sheaves.html",
      "relativePath": "geometry/algebraic/sheaves.md",
      "key": "v-52093884",
      "path": "/geometry/algebraic/sheaves.html",
      "headers": [
        {
          "level": 2,
          "title": "Invertible Sheaves or Line Bundles",
          "slug": "invertible-sheaves-or-line-bundles"
        },
        {
          "level": 3,
          "title": "The Tautological and Hyperplane Bundles",
          "slug": "the-tautological-and-hyperplane-bundles"
        }
      ],
      "lastUpdated": "11/25/2019, 8:35:35 PM"
    },
    {
      "title": "Varieties",
      "frontmatter": {},
      "regularPath": "/geometry/algebraic/varieties.html",
      "relativePath": "geometry/algebraic/varieties.md",
      "key": "v-1228cf5e",
      "path": "/geometry/algebraic/varieties.html",
      "headers": [
        {
          "level": 2,
          "title": "Quasi-Projective Varieties",
          "slug": "quasi-projective-varieties"
        },
        {
          "level": 3,
          "title": "Quasi-Projective Varieties",
          "slug": "quasi-projective-varieties-2"
        },
        {
          "level": 3,
          "title": "Morphisms",
          "slug": "morphisms"
        },
        {
          "level": 2,
          "title": "Birational Geometry",
          "slug": "birational-geometry"
        },
        {
          "level": 3,
          "title": "Projective Morphisms",
          "slug": "projective-morphisms"
        },
        {
          "level": 3,
          "title": "Birational Morphisms",
          "slug": "birational-morphisms"
        },
        {
          "level": 3,
          "title": "Rational Maps",
          "slug": "rational-maps"
        },
        {
          "level": 3,
          "title": "Birational Equivalence",
          "slug": "birational-equivalence"
        }
      ],
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Vector Bundles",
      "frontmatter": {},
      "regularPath": "/geometry/complex/vector-bundles.html",
      "relativePath": "geometry/complex/vector-bundles.md",
      "key": "v-71ced54a",
      "path": "/geometry/complex/vector-bundles.html",
      "headers": [
        {
          "level": 2,
          "title": "Properties",
          "slug": "properties"
        },
        {
          "level": 2,
          "title": "Pullback Bundles",
          "slug": "pullback-bundles"
        },
        {
          "level": 2,
          "title": "Direct Sum of Bundles",
          "slug": "direct-sum-of-bundles"
        },
        {
          "level": 2,
          "title": "Tensor Product of Bundles",
          "slug": "tensor-product-of-bundles"
        },
        {
          "level": 2,
          "title": "Exterior and Symmetric Powers of Bundles",
          "slug": "exterior-and-symmetric-powers-of-bundles"
        },
        {
          "level": 2,
          "title": "External Tensor Products of Bundles",
          "slug": "external-tensor-products-of-bundles"
        },
        {
          "level": 2,
          "title": "Dual Bundles",
          "slug": "dual-bundles"
        },
        {
          "level": 2,
          "title": "Determinant Bundles",
          "slug": "determinant-bundles"
        },
        {
          "level": 2,
          "title": "Projective Bundles",
          "slug": "projective-bundles"
        }
      ],
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Differential Geometry",
      "frontmatter": {},
      "regularPath": "/geometry/differential/connections.html",
      "relativePath": "geometry/differential/connections.md",
      "key": "v-a7f50cac",
      "path": "/geometry/differential/connections.html",
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Moment Maps",
      "frontmatter": {},
      "regularPath": "/geometry/symplectic/moment-maps.html",
      "relativePath": "geometry/symplectic/moment-maps.md",
      "key": "v-0221ba6c",
      "path": "/geometry/symplectic/moment-maps.html",
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "TODO:",
      "frontmatter": {},
      "regularPath": "/home.html",
      "relativePath": "home.md",
      "key": "v-1b49ce50",
      "path": "/home.html",
      "headers": [
        {
          "level": 2,
          "title": "Topics",
          "slug": "topics"
        },
        {
          "level": 2,
          "title": "Configuration",
          "slug": "configuration"
        }
      ],
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Miscellaneous",
      "frontmatter": {},
      "regularPath": "/miscellaneous/",
      "relativePath": "miscellaneous/README.md",
      "key": "v-c766915a",
      "path": "/miscellaneous/",
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Cheatsheets",
      "frontmatter": {},
      "regularPath": "/miscellaneous/linux.html",
      "relativePath": "miscellaneous/linux.md",
      "key": "v-1e91586c",
      "path": "/miscellaneous/linux.html",
      "headers": [
        {
          "level": 2,
          "title": "Linux Shell",
          "slug": "linux-shell"
        },
        {
          "level": 3,
          "title": "Directory and File Manipulation",
          "slug": "directory-and-file-manipulation"
        },
        {
          "level": 2,
          "title": "Miscellaneous",
          "slug": "miscellaneous"
        },
        {
          "level": 3,
          "title": "Local Zotero Website Publishing with Zotsite",
          "slug": "local-zotero-website-publishing-with-zotsite"
        },
        {
          "level": 2,
          "title": "Python",
          "slug": "python"
        },
        {
          "level": 3,
          "title": "Virtual Environments for Local Development",
          "slug": "virtual-environments-for-local-development"
        },
        {
          "level": 2,
          "title": "Git",
          "slug": "git"
        },
        {
          "level": 3,
          "title": "Setup",
          "slug": "setup"
        },
        {
          "level": 3,
          "title": "Setup & Initialisation",
          "slug": "setup-initialisation"
        },
        {
          "level": 3,
          "title": "Stage & Snapshot",
          "slug": "stage-snapshot"
        }
      ],
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Manuals and READMEs",
      "frontmatter": {},
      "regularPath": "/miscellaneous/manuals.html",
      "relativePath": "miscellaneous/manuals.md",
      "key": "v-441946ea",
      "path": "/miscellaneous/manuals.html",
      "lastUpdated": "11/25/2019, 8:35:35 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/miscellaneous/manuals/pypdfocr.html",
      "relativePath": "miscellaneous/manuals/pypdfocr.md",
      "key": "v-f3cfeab4",
      "path": "/miscellaneous/manuals/pypdfocr.html",
      "lastUpdated": "11/25/2019, 8:35:35 PM"
    },
    {
      "title": "Vuepress",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/miscellaneous/vuepress.html",
      "relativePath": "miscellaneous/vuepress.md",
      "key": "v-a9b8d84c",
      "path": "/miscellaneous/vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "Plugin Dependencies",
          "slug": "plugin-dependencies"
        },
        {
          "level": 3,
          "title": "vuepress-plugin-container",
          "slug": "vuepress-plugin-container"
        },
        {
          "level": 3,
          "title": "vuepress-plugin-latex",
          "slug": "vuepress-plugin-latex"
        }
      ],
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/physics/",
      "relativePath": "physics/README.md",
      "key": "v-6e194161",
      "path": "/physics/",
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "Gauge Theory",
      "frontmatter": {},
      "regularPath": "/physics/gauge.html",
      "relativePath": "physics/gauge.md",
      "key": "v-404fef6c",
      "path": "/physics/gauge.html",
      "lastUpdated": "11/25/2019, 8:35:35 PM"
    },
    {
      "title": "Geometric Quantisation",
      "frontmatter": {},
      "regularPath": "/physics/quantisation.html",
      "relativePath": "physics/quantisation.md",
      "key": "v-1aa2af14",
      "path": "/physics/quantisation.html",
      "headers": [
        {
          "level": 2,
          "title": "Prequantisation",
          "slug": "prequantisation"
        }
      ],
      "lastUpdated": "11/26/2019, 2:54:33 AM"
    },
    {
      "title": "String Theory",
      "frontmatter": {},
      "regularPath": "/physics/string.html",
      "relativePath": "physics/string.md",
      "key": "v-2c420cb8",
      "path": "/physics/string.html",
      "lastUpdated": "11/25/2019, 8:35:35 PM"
    },
    {
      "title": "Supersymmetry",
      "frontmatter": {},
      "regularPath": "/physics/supersymmetry.html",
      "relativePath": "physics/supersymmetry.md",
      "key": "v-1138a58a",
      "path": "/physics/supersymmetry.html",
      "lastUpdated": "11/25/2019, 8:35:35 PM"
    }
  ],
  "themeConfig": {
    "repo": "bencwbrown/vuepress-wiki",
    "editLinks": true,
    "docsDir": "packages/docs/docs",
    "smoothScroll": true,
    "locales": {
      "/": {
        "label": "English",
        "selectText": "Languages",
        "ariaLabel": "Select language",
        "editLinkText": "Edit this page on GitHub",
        "lastUpdated": "Last Updated",
        "nav": [
          {
            "text": "Geometry",
            "ariaLabel": "Geometry",
            "items": [
              {
                "text": "Geometry",
                "link": "/geometry/"
              },
              {
                "text": "Algebraic",
                "items": [
                  {
                    "text": "Varieties",
                    "link": "/geometry/algebraic/varieties.html"
                  },
                  {
                    "text": "Schemes",
                    "link": "/geometry/algebraic/schemes.html"
                  },
                  {
                    "text": "Sheaves",
                    "link": "/geometry/algebraic/sheaves.html"
                  },
                  {
                    "text": "Geometric Invariant Theory",
                    "link": "/geometry/algebraic/git.html"
                  }
                ]
              },
              {
                "text": "Complex",
                "items": [
                  {
                    "text": "Vector Bundles",
                    "link": "/geometry/complex/vector-bundles.html"
                  }
                ]
              },
              {
                "text": "Symplectic",
                "items": [
                  {
                    "text": "Moment Maps",
                    "link": "/geometry/symplectic/moment-maps.html"
                  }
                ]
              },
              {
                "text": "Differential",
                "items": [
                  {
                    "text": "Connections",
                    "link": "/geometry/differential/connections.html"
                  }
                ]
              }
            ]
          },
          {
            "text": "Algebra",
            "link": "/algebra/"
          },
          {
            "text": "Physics",
            "link": "/physics/"
          },
          {
            "text": "Miscellaneous",
            "link": "/miscellaneous/"
          }
        ],
        "sidebar": {
          "/geometry/": [
            {
              "title": "Algebraic Geometry",
              "collapsable": false,
              "sidebarDepth": 1,
              "children": [
                "./algebraic/varieties",
                "./algebraic/schemes",
                "./algebraic/sheaves",
                "./algebraic/git"
              ]
            },
            {
              "title": "Complex Geometry",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "./complex/vector-bundles"
              ]
            },
            {
              "title": "Symplectic Geometry",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "./symplectic/moment-maps"
              ]
            },
            {
              "title": "Differential Geometry",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "./differential/connections"
              ]
            }
          ],
          "/algebra/": [
            {
              "title": "Category Theory",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "category"
              ]
            },
            {
              "title": "Commutative Algebra",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "commutative"
              ]
            },
            {
              "title": "Group Theory",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "group"
              ]
            },
            {
              "title": "Non-Commutative Algebra",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "noncommutative"
              ]
            },
            {
              "title": "Representation Theory",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "representation"
              ]
            }
          ],
          "/physics/": [
            {
              "title": "Quantisation",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "./quantisation"
              ]
            },
            {
              "title": "String Theory",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "./string"
              ]
            }
          ],
          "/miscellaneous/": [
            {
              "title": "Linux",
              "collapsable": false,
              "sidebarDepth": 1,
              "children": [
                "./linux"
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "en-GB",
      "title": "Wiki",
      "description": "Personal wiki for my research",
      "path": "/"
    }
  }
}