/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Wiki",
        "tagLine": "Create and publish fast, feature-rich sites in minutes",
        "heroImage": "/icon.png",
        "actionText": "Enter the wiki! →",
        "actionLink": "/home"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-67bd9eb8",
      "path": "/",
      "headers": [
        {
          "level": 3,
          "title": "By Ben Brown",
          "slug": "by-ben-brown"
        }
      ]
    },
    {
      "title": "Config Reference",
      "frontmatter": {
        "sidebarDepth": 3,
        "sidebar": "auto"
      },
      "regularPath": "/algebra/",
      "relativePath": "algebra/README.md",
      "key": "v-35957706",
      "path": "/algebra/",
      "headers": [
        {
          "level": 2,
          "title": "Basic Config",
          "slug": "basic-config"
        },
        {
          "level": 3,
          "title": "base",
          "slug": "base"
        },
        {
          "level": 3,
          "title": "title",
          "slug": "title"
        },
        {
          "level": 3,
          "title": "description",
          "slug": "description"
        },
        {
          "level": 3,
          "title": "head",
          "slug": "head"
        },
        {
          "level": 3,
          "title": "host",
          "slug": "host"
        },
        {
          "level": 3,
          "title": "port",
          "slug": "port"
        },
        {
          "level": 3,
          "title": "temp",
          "slug": "temp"
        },
        {
          "level": 3,
          "title": "dest",
          "slug": "dest"
        },
        {
          "level": 3,
          "title": "locales",
          "slug": "locales"
        },
        {
          "level": 3,
          "title": "shouldPrefetch",
          "slug": "shouldprefetch"
        },
        {
          "level": 3,
          "title": "cache",
          "slug": "cache"
        },
        {
          "level": 3,
          "title": "extraWatchFiles",
          "slug": "extrawatchfiles"
        },
        {
          "level": 3,
          "title": "patterns",
          "slug": "patterns"
        },
        {
          "level": 2,
          "title": "Styling",
          "slug": "styling"
        },
        {
          "level": 3,
          "title": "palette.styl",
          "slug": "palette-styl"
        },
        {
          "level": 3,
          "title": "index.styl",
          "slug": "index-styl"
        },
        {
          "level": 2,
          "title": "Theming",
          "slug": "theming"
        },
        {
          "level": 3,
          "title": "theme",
          "slug": "theme"
        },
        {
          "level": 3,
          "title": "themeConfig",
          "slug": "themeconfig"
        },
        {
          "level": 2,
          "title": "Pluggable",
          "slug": "pluggable"
        },
        {
          "level": 3,
          "title": "plugins",
          "slug": "plugins"
        },
        {
          "level": 2,
          "title": "Markdown",
          "slug": "markdown"
        },
        {
          "level": 3,
          "title": "markdown.lineNumbers",
          "slug": "markdown-linenumbers"
        },
        {
          "level": 3,
          "title": "markdown.slugify",
          "slug": "markdown-slugify"
        },
        {
          "level": 3,
          "title": "markdown.anchor",
          "slug": "markdown-anchor"
        },
        {
          "level": 3,
          "title": "markdown.externalLinks",
          "slug": "markdown-externallinks"
        },
        {
          "level": 3,
          "title": "markdown.toc",
          "slug": "markdown-toc"
        },
        {
          "level": 3,
          "title": "markdown.plugins",
          "slug": "markdown-plugins"
        },
        {
          "level": 3,
          "title": "markdown.extendMarkdown",
          "slug": "markdown-extendmarkdown"
        },
        {
          "level": 3,
          "title": "markdown.extractHeaders",
          "slug": "markdown-extractheaders"
        },
        {
          "level": 2,
          "title": "Build Pipeline",
          "slug": "build-pipeline"
        },
        {
          "level": 3,
          "title": "postcss",
          "slug": "postcss"
        },
        {
          "level": 3,
          "title": "Stylus",
          "slug": "stylus"
        },
        {
          "level": 3,
          "title": "scss",
          "slug": "scss"
        },
        {
          "level": 3,
          "title": "Sass",
          "slug": "sass"
        },
        {
          "level": 3,
          "title": "less",
          "slug": "less"
        },
        {
          "level": 3,
          "title": "configureWebpack",
          "slug": "configurewebpack"
        },
        {
          "level": 3,
          "title": "chainWebpack",
          "slug": "chainwebpack"
        },
        {
          "level": 2,
          "title": "Browser Compatibility",
          "slug": "browser-compatibility"
        },
        {
          "level": 3,
          "title": "evergreen",
          "slug": "evergreen"
        }
      ]
    },
    {
      "title": "Category Theory",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/algebra/category.html",
      "relativePath": "algebra/category.md",
      "key": "v-38e50476",
      "path": "/algebra/category.html",
      "headers": [
        {
          "level": 2,
          "title": "Constructions",
          "slug": "constructions"
        },
        {
          "level": 3,
          "title": "Coproduct",
          "slug": "coproduct"
        }
      ]
    },
    {
      "title": "Commutative Algebra",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/algebra/commutative.html",
      "relativePath": "algebra/commutative.md",
      "key": "v-39371d7a",
      "path": "/algebra/commutative.html",
      "headers": [
        {
          "level": 2,
          "title": "Algebras",
          "slug": "algebras"
        }
      ]
    },
    {
      "title": "Group Theory",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/algebra/group.html",
      "relativePath": "algebra/group.md",
      "key": "v-6e377c63",
      "path": "/algebra/group.html",
      "headers": [
        {
          "level": 2,
          "title": "Actions",
          "slug": "actions"
        },
        {
          "level": 2,
          "title": "Group Action",
          "slug": "group-action"
        },
        {
          "level": 3,
          "title": "Free Action",
          "slug": "free-action"
        },
        {
          "level": 3,
          "title": "Semifree Action",
          "slug": "semifree-action"
        },
        {
          "level": 2,
          "title": "Linear Algebraic Groups",
          "slug": "linear-algebraic-groups"
        },
        {
          "level": 3,
          "title": "Affine Algebraic Group",
          "slug": "affine-algebraic-group"
        },
        {
          "level": 3,
          "title": "Borel Subgroup",
          "slug": "borel-subgroup"
        }
      ]
    },
    {
      "title": "Lie Theory",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/algebra/lie.html",
      "relativePath": "algebra/lie.md",
      "key": "v-19f2d7fa",
      "path": "/algebra/lie.html"
    },
    {
      "title": "Non-Commutative Algebra",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/algebra/noncommutative.html",
      "relativePath": "algebra/noncommutative.md",
      "key": "v-6512bae7",
      "path": "/algebra/noncommutative.html"
    },
    {
      "title": "Representation Theory",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/algebra/representation.html",
      "relativePath": "algebra/representation.md",
      "key": "v-7d51f767",
      "path": "/algebra/representation.html",
      "headers": [
        {
          "level": 2,
          "title": "Constructions",
          "slug": "constructions"
        },
        {
          "level": 3,
          "title": "Tensor Product",
          "slug": "tensor-product"
        }
      ]
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/geometry/",
      "relativePath": "geometry/README.md",
      "key": "v-93f29fb0",
      "path": "/geometry/",
      "headers": [
        {
          "level": 2,
          "title": "How It Works",
          "slug": "how-it-works"
        },
        {
          "level": 2,
          "title": "Features",
          "slug": "features"
        },
        {
          "level": 2,
          "title": "Why Not ...?",
          "slug": "why-not"
        },
        {
          "level": 3,
          "title": "Nuxt",
          "slug": "nuxt"
        },
        {
          "level": 3,
          "title": "Docsify / Docute",
          "slug": "docsify-docute"
        },
        {
          "level": 3,
          "title": "Hexo",
          "slug": "hexo"
        },
        {
          "level": 3,
          "title": "GitBook",
          "slug": "gitbook"
        }
      ]
    },
    {
      "title": "Algebraic Geometry",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/geometry/algebraic/algebraic.html",
      "relativePath": "geometry/algebraic/algebraic.md",
      "key": "v-e514d642",
      "path": "/geometry/algebraic/algebraic.html",
      "headers": [
        {
          "level": 2,
          "title": "Algebraic Varieties",
          "slug": "algebraic-varieties"
        },
        {
          "level": 3,
          "title": "Quasi-Projective Varieties",
          "slug": "quasi-projective-varieties"
        },
        {
          "level": 3,
          "title": "Morphisms",
          "slug": "morphisms"
        },
        {
          "level": 2,
          "title": "Birational Geometry",
          "slug": "birational-geometry"
        },
        {
          "level": 3,
          "title": "Projective Morphisms",
          "slug": "projective-morphisms"
        },
        {
          "level": 3,
          "title": "Birational Morphisms",
          "slug": "birational-morphisms"
        },
        {
          "level": 3,
          "title": "Rational Maps",
          "slug": "rational-maps"
        },
        {
          "level": 3,
          "title": "Birational Equivalence",
          "slug": "birational-equivalence"
        },
        {
          "level": 2,
          "title": "Types of Morphisms",
          "slug": "types-of-morphisms"
        },
        {
          "level": 3,
          "title": "Closed Embeddings",
          "slug": "closed-embeddings"
        }
      ]
    },
    {
      "title": "Geometric Invariant Theory",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/geometry/algebraic/git.html",
      "relativePath": "geometry/algebraic/git.md",
      "key": "v-ad713182",
      "path": "/geometry/algebraic/git.html",
      "headers": [
        {
          "level": 2,
          "title": "Linearisations",
          "slug": "linearisations"
        },
        {
          "level": 3,
          "title": "$G$-linearisation",
          "slug": "g-linearisation"
        },
        {
          "level": 3,
          "title": "Picard Groups of Products",
          "slug": "picard-groups-of-products"
        },
        {
          "level": 2,
          "title": "Algebraic Symplectic Reduction",
          "slug": "algebraic-symplectic-reduction"
        },
        {
          "level": 3,
          "title": "Algebraic Symplectic Reduction",
          "slug": "algebraic-symplectic-reduction-2"
        }
      ]
    },
    {
      "title": "Schemes",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/geometry/algebraic/schemes.html",
      "relativePath": "geometry/algebraic/schemes.md",
      "key": "v-5c45b9f2",
      "path": "/geometry/algebraic/schemes.html",
      "headers": [
        {
          "level": 2,
          "title": "Projective Schemes",
          "slug": "projective-schemes"
        },
        {
          "level": 3,
          "title": "The Proj Construction",
          "slug": "the-proj-construction"
        },
        {
          "level": 3,
          "title": "Projective Scheme(s) over an Affine Scheme",
          "slug": "projective-scheme-s-over-an-affine-scheme"
        },
        {
          "level": 3,
          "title": "Truncated Rings and the Veronese Embedding",
          "slug": "truncated-rings-and-the-veronese-embedding"
        },
        {
          "level": 2,
          "title": "References",
          "slug": "references"
        }
      ]
    },
    {
      "title": "Sheaves",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/geometry/algebraic/sheaves.html",
      "relativePath": "geometry/algebraic/sheaves.md",
      "key": "v-34fbce3d",
      "path": "/geometry/algebraic/sheaves.html",
      "headers": [
        {
          "level": 2,
          "title": "Invertible Sheaves or Line Bundles",
          "slug": "invertible-sheaves-or-line-bundles"
        },
        {
          "level": 3,
          "title": "The Tautological and Hyperplane Bundles",
          "slug": "the-tautological-and-hyperplane-bundles"
        }
      ]
    },
    {
      "title": "Varieties",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/geometry/algebraic/varieties.html",
      "relativePath": "geometry/algebraic/varieties.md",
      "key": "v-69f7e097",
      "path": "/geometry/algebraic/varieties.html",
      "headers": [
        {
          "level": 2,
          "title": "Quasi-Projective Varieties",
          "slug": "quasi-projective-varieties"
        },
        {
          "level": 3,
          "title": "Quasi-Projective Varieties",
          "slug": "quasi-projective-varieties-2"
        },
        {
          "level": 3,
          "title": "Morphisms",
          "slug": "morphisms"
        },
        {
          "level": 2,
          "title": "Birational Geometry",
          "slug": "birational-geometry"
        },
        {
          "level": 3,
          "title": "Projective Morphisms",
          "slug": "projective-morphisms"
        },
        {
          "level": 3,
          "title": "Birational Morphisms",
          "slug": "birational-morphisms"
        },
        {
          "level": 3,
          "title": "Rational Maps",
          "slug": "rational-maps"
        },
        {
          "level": 3,
          "title": "Birational Equivalence",
          "slug": "birational-equivalence"
        }
      ]
    },
    {
      "title": "Complex Geometry",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/geometry/complex/complex.html",
      "relativePath": "geometry/complex/complex.md",
      "key": "v-7a9346a7",
      "path": "/geometry/complex/complex.html",
      "headers": [
        {
          "level": 2,
          "title": "Vector Bundles",
          "slug": "vector-bundles"
        },
        {
          "level": 3,
          "title": "Properties",
          "slug": "properties"
        },
        {
          "level": 2,
          "title": "Constructions of Vector Bundles",
          "slug": "constructions-of-vector-bundles"
        },
        {
          "level": 3,
          "title": "Pullback Bundles",
          "slug": "pullback-bundles"
        },
        {
          "level": 3,
          "title": "Direct Sum of Bundles",
          "slug": "direct-sum-of-bundles"
        },
        {
          "level": 3,
          "title": "Tensor Product of Bundles",
          "slug": "tensor-product-of-bundles"
        },
        {
          "level": 3,
          "title": "Exterior and Symmetric Powers of Bundles",
          "slug": "exterior-and-symmetric-powers-of-bundles"
        },
        {
          "level": 3,
          "title": "External Tensor Products of Bundles",
          "slug": "external-tensor-products-of-bundles"
        },
        {
          "level": 3,
          "title": "Dual Bundles",
          "slug": "dual-bundles"
        },
        {
          "level": 3,
          "title": "Determinant Bundles",
          "slug": "determinant-bundles"
        },
        {
          "level": 3,
          "title": "Projective Bundles",
          "slug": "projective-bundles"
        }
      ]
    },
    {
      "title": "Differential Geometry",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/geometry/differential/differential.html",
      "relativePath": "geometry/differential/differential.md",
      "key": "v-365cddaa",
      "path": "/geometry/differential/differential.html"
    },
    {
      "title": "Symplectic Geometry",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/geometry/symplectic/symplectic.html",
      "relativePath": "geometry/symplectic/symplectic.md",
      "key": "v-0e3f54ab",
      "path": "/geometry/symplectic/symplectic.html",
      "headers": [
        {
          "level": 2,
          "title": "Moment Maps",
          "slug": "moment-maps"
        },
        {
          "level": 2,
          "title": "Symplectic Cutting",
          "slug": "symplectic-cutting"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/home.html",
      "relativePath": "home.md",
      "key": "v-0bd0e011",
      "path": "/home.html"
    },
    {
      "title": "Manuals and READMEs",
      "frontmatter": {},
      "regularPath": "/miscellaneous/manuals.html",
      "relativePath": "miscellaneous/manuals.md",
      "key": "v-239fffe3",
      "path": "/miscellaneous/manuals.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/miscellaneous/manuals/pypdfocr.html",
      "relativePath": "miscellaneous/manuals/pypdfocr.md",
      "key": "v-5119d75f",
      "path": "/miscellaneous/manuals/pypdfocr.html"
    },
    {
      "title": "Linux Programming",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/miscellaneous/programming/linux.html",
      "relativePath": "miscellaneous/programming/linux.md",
      "key": "v-cc9d6bfa",
      "path": "/miscellaneous/programming/linux.html",
      "headers": [
        {
          "level": 2,
          "title": "Cheatsheets",
          "slug": "cheatsheets"
        },
        {
          "level": 3,
          "title": "Linux Shell",
          "slug": "linux-shell"
        },
        {
          "level": 3,
          "title": "Miscellaneous",
          "slug": "miscellaneous"
        },
        {
          "level": 3,
          "title": "Python",
          "slug": "python"
        },
        {
          "level": 3,
          "title": "Git",
          "slug": "git"
        }
      ]
    },
    {
      "title": "Vuepress",
      "frontmatter": {
        "lang": "en-GB"
      },
      "regularPath": "/miscellaneous/programming/vuepress.html",
      "relativePath": "miscellaneous/programming/vuepress.md",
      "key": "v-8cbe56b2",
      "path": "/miscellaneous/programming/vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "Plugin Dependencies",
          "slug": "plugin-dependencies"
        },
        {
          "level": 3,
          "title": "vuepress-plugin-container",
          "slug": "vuepress-plugin-container"
        },
        {
          "level": 3,
          "title": "vuepress-plugin-latex",
          "slug": "vuepress-plugin-latex"
        }
      ]
    },
    {
      "title": "Plugin",
      "frontmatter": {},
      "regularPath": "/physics/",
      "relativePath": "physics/README.md",
      "key": "v-b8e4eb70",
      "path": "/physics/"
    },
    {
      "title": "Gauge Theory",
      "frontmatter": {},
      "regularPath": "/physics/gauge.html",
      "relativePath": "physics/gauge.md",
      "key": "v-ba0c597a",
      "path": "/physics/gauge.html"
    },
    {
      "title": "Quantisation",
      "frontmatter": {},
      "regularPath": "/physics/quantisation.html",
      "relativePath": "physics/quantisation.md",
      "key": "v-9f5d68a2",
      "path": "/physics/quantisation.html",
      "headers": [
        {
          "level": 2,
          "title": "Geometric Quantisation",
          "slug": "geometric-quantisation"
        }
      ]
    },
    {
      "title": "String Theory",
      "frontmatter": {},
      "regularPath": "/physics/string.html",
      "relativePath": "physics/string.md",
      "key": "v-6bb9ea5d",
      "path": "/physics/string.html"
    },
    {
      "title": "Supersymmetry",
      "frontmatter": {},
      "regularPath": "/physics/supersymmetry.html",
      "relativePath": "physics/supersymmetry.md",
      "key": "v-1e8142fa",
      "path": "/physics/supersymmetry.html"
    }
  ],
  "themeConfig": {
    "repo": "bencwbrown/vuepress-wiki",
    "editLinks": true,
    "docsDir": "packages/docs/docs",
    "smoothScroll": true,
    "locales": {
      "/": {
        "label": "English",
        "selectText": "Languages",
        "ariaLabel": "Select language",
        "editLinkText": "Edit this page on GitHub",
        "lastUpdated": "Last Updated",
        "nav": [
          {
            "text": "Geometry",
            "ariaLabel": "Geometry",
            "items": [
              {
                "text": "Algebraic",
                "items": [
                  {
                    "text": "Varieties",
                    "link": "/geometry/algebraic/varieties.html"
                  },
                  {
                    "text": "Schemes",
                    "link": "/geometry/algebraic/schemes.html"
                  },
                  {
                    "text": "Geometric Invariant Theory",
                    "link": "/geometry/algebraic/git.html"
                  }
                ]
              },
              {
                "text": "Complex",
                "items": [
                  {
                    "text": "Vector Bundles",
                    "link": "/geometry/complex/vector-bundles.html"
                  }
                ]
              },
              {
                "text": "Symplectic",
                "items": [
                  {
                    "text": "Moment Maps",
                    "link": "/geometry/symplectic/moment-maps.html"
                  }
                ]
              },
              {
                "text": "Differential",
                "items": [
                  {
                    "text": "Connections",
                    "link": "/geometry/differential/connections.html"
                  }
                ]
              }
            ]
          },
          {
            "text": "Algebra",
            "link": "/algebra/"
          },
          {
            "text": "Physics",
            "link": "/physics/"
          },
          {
            "text": "Miscellaneous",
            "link": "/miscellaneous/"
          }
        ],
        "sidebar": {
          "/geometry/": [
            {
              "title": "Algebraic",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "varieties",
                "schemes",
                "sheaves",
                "git"
              ]
            },
            {
              "title": "Complex",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "vector-bundles"
              ]
            },
            {
              "title": "Symplectic",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "moment-maps"
              ]
            },
            {
              "title": "Differential",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "connections"
              ]
            }
          ],
          "/algebra/": [
            {
              "title": "Commutative",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": []
            },
            {
              "title": "Non-Commutative",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": []
            },
            {
              "title": "Representation Theory",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": [
                "algebras"
              ]
            },
            {
              "collapsable": false,
              "sidebarDepth": 2,
              "children": []
            },
            {
              "collapsable": false,
              "sidebarDepth": 2,
              "children": []
            }
          ],
          "/physics/": [
            {
              "title": "Theme",
              "collapsable": false,
              "sidebarDepth": 2,
              "children": []
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "en-GB",
      "title": "Wiki",
      "description": "Personal wiki for my research",
      "path": "/"
    }
  }
}